# Generated by Django 2.1.1 on 2018-09-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.FloatField(max_length=10)),
                ('quantity', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity_all', models.IntegerField(max_length=20)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.Phones')),
            ],
        ),
    ]
