# Generated by Django 2.1.1 on 2018-09-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20180910_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='type',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
