# Generated by Django 2.1.1 on 2018-09-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20180910_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Phones', to_field='Brand'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='Brand',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
