# Generated by Django 2.1.1 on 2018-09-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20180910_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default='pass', max_length=20),
            preserve_default=False,
        ),
    ]
